export const ROLES = [
  'SUPER_ADMIN',
  'HR_ADMIN',
  'HR_MANAGER',
  'MANAGER',
  'FINANCE',
  'RECRUITER',
  'EMPLOYEE',
] as const;

export type AppRole = (typeof ROLES)[number];

export const PERMISSIONS = {
  EMPLOYEE_CREATE: 'employee:create',
  EMPLOYEE_READ_ANY: 'employee:read:any',
  EMPLOYEE_READ_TEAM: 'employee:read:team',
  EMPLOYEE_READ_OWN: 'employee:read:own',
  EMPLOYEE_UPDATE: 'employee:update',
  EMPLOYEE_STATUS: 'employee:status',
  EMPLOYEE_DELETE: 'employee:delete',

  DEPARTMENT_MANAGE: 'department:manage',
  DEPARTMENT_READ: 'department:read',

  DESIGNATION_MANAGE: 'designation:manage',
  DESIGNATION_READ: 'designation:read',

  USER_READ: 'user:read',
  USER_MANAGE: 'user:manage',

  ATTENDANCE_MARK: 'attendance:mark',
  ATTENDANCE_READ_OWN: 'attendance:read:own',
  ATTENDANCE_READ_TEAM: 'attendance:read:team',
  ATTENDANCE_READ_ANY: 'attendance:read:any',
  ATTENDANCE_CORRECT: 'attendance:correct',
  ATTENDANCE_IMPORT: 'attendance:import',

  LEAVE_APPLY: 'leave:apply',
  LEAVE_READ_OWN: 'leave:read:own',
  LEAVE_READ_ANY: 'leave:read:any',
  LEAVE_APPROVE_MANAGER: 'leave:approve:manager',
  LEAVE_APPROVE_HR: 'leave:approve:hr',
  LEAVE_MANAGE: 'leave:manage',

  LEAVE_TYPE_MANAGE: 'leaveType:manage',
  LEAVE_TYPE_READ: 'leaveType:read',
  LEAVE_BALANCE_MANAGE: 'leaveBalance:manage',

  HOLIDAY_MANAGE: 'holiday:manage',
  HOLIDAY_READ: 'holiday:read',

  SALARY_READ_OWN: 'salary:read:own',
  SALARY_READ_ANY: 'salary:read:any',
  SALARY_MANAGE: 'salary:manage',

  PAYROLL_PROCESS: 'payroll:process',
  PAYROLL_LOCK: 'payroll:lock',
  PAYROLL_READ: 'payroll:read',
  PAYSLIP_READ_OWN: 'payslip:read:own',
  PAYSLIP_READ_ANY: 'payslip:read:any',

  DOCUMENT_UPLOAD: 'document:upload',
  DOCUMENT_READ_OWN: 'document:read:own',
  DOCUMENT_READ_ANY: 'document:read:any',
  DOCUMENT_VERIFY: 'document:verify',
  DOCUMENT_DELETE: 'document:delete',

  JOB_MANAGE: 'job:manage',
  CANDIDATE_MANAGE: 'candidate:manage',
  INTERVIEW_MANAGE: 'interview:manage',
  INTERVIEW_FEEDBACK: 'interview:feedback',
  OFFER_MANAGE: 'offer:manage',

  GOAL_MANAGE_OWN: 'goal:manage:own',
  GOAL_MANAGE_TEAM: 'goal:manage:team',
  GOAL_MANAGE_ANY: 'goal:manage:any',
  REVIEW_READ_OWN: 'review:read:own',
  REVIEW_MANAGE_TEAM: 'review:manage:team',
  REVIEW_MANAGE_ANY: 'review:manage:any',

  ANNOUNCEMENT_MANAGE: 'announcement:manage',
  ANNOUNCEMENT_READ: 'announcement:read',

  NOTIFICATION_READ_OWN: 'notification:read:own',

  REPORTS_HR: 'reports:hr',
  REPORTS_FINANCE: 'reports:finance',

  AUDIT_READ: 'audit:read',
  SETTINGS_MANAGE: 'settings:manage',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const SELF_SERVICE: Permission[] = [
  PERMISSIONS.EMPLOYEE_READ_OWN,
  PERMISSIONS.ATTENDANCE_MARK,
  PERMISSIONS.ATTENDANCE_READ_OWN,
  PERMISSIONS.LEAVE_APPLY,
  PERMISSIONS.LEAVE_READ_OWN,
  PERMISSIONS.LEAVE_TYPE_READ,
  PERMISSIONS.HOLIDAY_READ,
  PERMISSIONS.DOCUMENT_UPLOAD,
  PERMISSIONS.DOCUMENT_READ_OWN,
  PERMISSIONS.SALARY_READ_OWN,
  PERMISSIONS.PAYSLIP_READ_OWN,
  PERMISSIONS.GOAL_MANAGE_OWN,
  PERMISSIONS.REVIEW_READ_OWN,
  PERMISSIONS.ANNOUNCEMENT_READ,
  PERMISSIONS.NOTIFICATION_READ_OWN,
];

const HR_STAFF: Permission[] = [
  ...SELF_SERVICE,
  PERMISSIONS.EMPLOYEE_CREATE,
  PERMISSIONS.EMPLOYEE_READ_ANY,
  PERMISSIONS.EMPLOYEE_UPDATE,
  PERMISSIONS.EMPLOYEE_STATUS,
  PERMISSIONS.DEPARTMENT_MANAGE,
  PERMISSIONS.DEPARTMENT_READ,
  PERMISSIONS.DESIGNATION_MANAGE,
  PERMISSIONS.DESIGNATION_READ,
  PERMISSIONS.USER_READ,
  PERMISSIONS.ATTENDANCE_READ_ANY,
  PERMISSIONS.ATTENDANCE_CORRECT,
  PERMISSIONS.ATTENDANCE_IMPORT,
  PERMISSIONS.LEAVE_READ_ANY,
  PERMISSIONS.LEAVE_APPROVE_MANAGER,
  PERMISSIONS.LEAVE_APPROVE_HR,
  PERMISSIONS.LEAVE_MANAGE,
  PERMISSIONS.LEAVE_TYPE_MANAGE,
  PERMISSIONS.LEAVE_BALANCE_MANAGE,
  PERMISSIONS.HOLIDAY_MANAGE,
  PERMISSIONS.DOCUMENT_READ_ANY,
  PERMISSIONS.DOCUMENT_VERIFY,
  PERMISSIONS.DOCUMENT_DELETE,
  PERMISSIONS.ANNOUNCEMENT_MANAGE,
  PERMISSIONS.SALARY_READ_ANY,
  PERMISSIONS.PAYSLIP_READ_ANY,
  PERMISSIONS.JOB_MANAGE,
  PERMISSIONS.CANDIDATE_MANAGE,
  PERMISSIONS.INTERVIEW_MANAGE,
  PERMISSIONS.OFFER_MANAGE,
  PERMISSIONS.GOAL_MANAGE_ANY,
  PERMISSIONS.REVIEW_MANAGE_ANY,
  PERMISSIONS.REPORTS_HR,
  PERMISSIONS.SETTINGS_MANAGE,
];

export const ROLE_PERMISSIONS: Record<AppRole, readonly Permission[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),

  HR_ADMIN: HR_STAFF,

  HR_MANAGER: [
    ...SELF_SERVICE,
    PERMISSIONS.EMPLOYEE_READ_ANY,
    PERMISSIONS.EMPLOYEE_UPDATE,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.DESIGNATION_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.ATTENDANCE_READ_ANY,
    PERMISSIONS.ATTENDANCE_CORRECT,
    PERMISSIONS.LEAVE_READ_ANY,
    PERMISSIONS.LEAVE_APPROVE_MANAGER,
    PERMISSIONS.LEAVE_APPROVE_HR,
    PERMISSIONS.DOCUMENT_READ_ANY,
    PERMISSIONS.ANNOUNCEMENT_MANAGE,
    PERMISSIONS.JOB_MANAGE,
    PERMISSIONS.CANDIDATE_MANAGE,
    PERMISSIONS.INTERVIEW_MANAGE,
    PERMISSIONS.GOAL_MANAGE_TEAM,
    PERMISSIONS.GOAL_MANAGE_ANY,
    PERMISSIONS.REVIEW_MANAGE_TEAM,
    PERMISSIONS.REVIEW_MANAGE_ANY,
    PERMISSIONS.REPORTS_HR,
  ],

  MANAGER: [
    ...SELF_SERVICE,
    PERMISSIONS.EMPLOYEE_READ_TEAM,
    PERMISSIONS.EMPLOYEE_UPDATE,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.DESIGNATION_READ,
    PERMISSIONS.ATTENDANCE_READ_TEAM,
    PERMISSIONS.LEAVE_READ_ANY,
    PERMISSIONS.LEAVE_APPROVE_MANAGER,
    PERMISSIONS.GOAL_MANAGE_TEAM,
    PERMISSIONS.REVIEW_MANAGE_TEAM,
    PERMISSIONS.INTERVIEW_FEEDBACK,
  ],

  FINANCE: [
    ...SELF_SERVICE,
    PERMISSIONS.EMPLOYEE_READ_ANY,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.DESIGNATION_READ,
    PERMISSIONS.ATTENDANCE_READ_ANY,
    PERMISSIONS.SALARY_READ_ANY,
    PERMISSIONS.SALARY_MANAGE,
    PERMISSIONS.PAYROLL_PROCESS,
    PERMISSIONS.PAYROLL_LOCK,
    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.PAYSLIP_READ_ANY,
    PERMISSIONS.REPORTS_FINANCE,
  ],

  RECRUITER: [
    ...SELF_SERVICE,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_READ_ANY,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.DESIGNATION_READ,
    PERMISSIONS.JOB_MANAGE,
    PERMISSIONS.CANDIDATE_MANAGE,
    PERMISSIONS.INTERVIEW_MANAGE,
    PERMISSIONS.INTERVIEW_FEEDBACK,
    PERMISSIONS.OFFER_MANAGE,
  ],

  EMPLOYEE: SELF_SERVICE,
};

export function hasPermission(role: string, permission: Permission): boolean {
  const permissions = ROLE_PERMISSIONS[role as AppRole];
  return permissions ? permissions.includes(permission) : false;
}

export function hasAnyPermission(role: string, permissions: Permission[]): boolean {
  return permissions.some((permission) => hasPermission(role, permission));
}

export function hasAllPermissions(role: string, permissions: Permission[]): boolean {
  return permissions.every((permission) => hasPermission(role, permission));
}

export function isAppRole(value: string): value is AppRole {
  return (ROLES as readonly string[]).includes(value);
}
